server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/currency?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  redis:
      host: 127.0.0.1
      port: 6379
      # password:  默认没有密码，生产环境一定要设置密码
      # 连接超时时间（ms）
      timeout: 10000ms
      # Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
      database: 0
      jedis:
        pool:
          # 连接池最大连接数（使用负值表示没有限制） 默认 8
          max-active: 10
          # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
          max-wait: -1
          # 连接池中的最大空闲连接 默认 8
          max-idle: 8
          # 连接池中的最小空闲连接 默认 0
          min-idle: 0



